### ISSUE TITLE
一开始用就报异常

### ISSUE THREAD

**Issue by godsoul** [shawjia/geektime-cli#1]
异常信息 hrow new TypeError('cellphone/password should be string'); 这个密码在哪里设置啊，geektime login 这样设置，也是报这个异常的，只要执行命令就报这个异常的

**Comment by shawjia** [comment]
@godsoul
1. `geektime login 手机 密码`
2. `geektime info` 检查是否配置成功

**Comment by godsoul** [comment]
任何命令都报错的，应该是mac下的原因

**Comment by shawjia** [comment]
@godsoul 请截图。我用的就是 macOS。

**Comment by godsoul** [comment]
![image](https://user-images.githubusercontent.com/3104500/47129865-aeefa300-d2c9-11e8-8a23-b8c80e8539a0.png)

**Comment by shawjia** [comment]
@godsoul 试着将你的密码用单引号扩起来 'password'，还是不行，提供一下你的版本
`node --version`
`geektime --version`

**Comment by godsoul** [comment]
还是不行的，node版本 v10.6.0 geektime 是拉的最新的

**Comment by shawjia** [comment]
@godsoul 新版本已经修复，请安装最新版本 2.0.2。
