### ISSUE TITLE
crypto.createCipher is deprecated

### ISSUE THREAD

**Issue by jostyee** [shawjia/geektime-cli#3]
```
$ geektime login mobile password
login info saved 😊
(node:16608) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
```

**Comment by shawjia** [comment]
@jostyee well, it's a documentation-only deprecation in the latest LTS version.
I don't think it's the right time to fix that. 
I suggest you use Node.js v10.13.0   (Latest LTS: Dubnium).
https://github.com/sindresorhus/conf/blob/master/index.js#L163
